@0xfc485bf574db512c; # unique file ID, generated by `capnp id`

$import "/capnp/c++.capnp".namespace("koinos::rpc");

using Go = import "/go.capnp";
$Go.package("rpc");
$Go.import("koinos/rpc");

struct ErrorResponse {
   errorText @0 :Text;
   errorData @1 :Text;
}
